package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class RegionDefaults
{
  private static void a(Region paramRegion, String paramString1, String paramString2)
  {
    Map localMap1 = paramRegion.aoS;
    Map localMap2 = paramRegion.aoT;
    paramRegion = paramRegion.aoU;
    localMap1.put(paramString1, paramString2);
    localMap2.put(paramString1, Boolean.valueOf(false));
    paramRegion.put(paramString1, Boolean.valueOf(true));
  }
  
  public static List<Region> jP()
  {
    ArrayList localArrayList = new ArrayList();
    Region localRegion = new Region("ap-northeast-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "s3", "s3-ap-northeast-1.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.ap-northeast-1.amazonaws.com");
    a(localRegion, "sdb", "sdb.ap-northeast-1.amazonaws.com");
    a(localRegion, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.ap-northeast-1.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.ap-northeast-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-1.amazonaws.com");
    a(localRegion, "lambda", "lambda.ap-northeast-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.ap-northeast-1.amazonaws.com");
    a(localRegion, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com");
    a(localRegion, "kms", "kms.ap-northeast-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.ap-northeast-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.ap-northeast-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com");
    a(localRegion, "sns", "sns.ap-northeast-1.amazonaws.com");
    a(localRegion, "iot", "iot.ap-northeast-1.amazonaws.com");
    localRegion = new Region("ap-northeast-2", "");
    localArrayList.add(localRegion);
    a(localRegion, "dynamodb", "dynamodb.ap-northeast-2.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.ap-northeast-2.amazonaws.com");
    a(localRegion, "kms", "kms.ap-northeast-2.amazonaws.com");
    a(localRegion, "sns", "sns.ap-northeast-2.amazonaws.com");
    a(localRegion, "lambda", "lambda.ap-northeast-2.amazonaws.com");
    a(localRegion, "s3", "s3.ap-northeast-2.amazonaws.com");
    a(localRegion, "iot", "iot.ap-northeast-2.amazonaws.com");
    a(localRegion, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com");
    a(localRegion, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com");
    a(localRegion, "sqs", "sqs.ap-northeast-2.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.ap-northeast-2.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.ap-northeast-2.amazonaws.com");
    a(localRegion, "ec2", "ec2.ap-northeast-2.amazonaws.com");
    a(localRegion, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-2.amazonaws.com");
    a(localRegion, "sts", "sts.ap-northeast-2.amazonaws.com");
    localRegion = new Region("ap-south-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "autoscaling", "autoscaling.ap-south-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.ap-south-1.amazonaws.com");
    a(localRegion, "kms", "kms.ap-south-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.ap-south-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.ap-south-1.amazonaws.com");
    a(localRegion, "sns", "sns.ap-south-1.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.ap-south-1.amazonaws.com");
    a(localRegion, "s3", "s3.ap-south-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.ap-south-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    localRegion = new Region("ap-southeast-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "kinesis", "kinesis.ap-southeast-1.amazonaws.com");
    a(localRegion, "sns", "sns.ap-southeast-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.ap-southeast-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-1.amazonaws.com");
    a(localRegion, "sdb", "sdb.ap-southeast-1.amazonaws.com");
    a(localRegion, "lambda", "lambda.ap-southeast-1.amazonaws.com");
    a(localRegion, "s3", "s3-ap-southeast-1.amazonaws.com");
    a(localRegion, "iot", "iot.ap-southeast-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.ap-southeast-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "kms", "kms.ap-southeast-1.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.ap-southeast-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.ap-southeast-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.ap-southeast-1.amazonaws.com");
    localRegion = new Region("ap-southeast-2", "");
    localArrayList.add(localRegion);
    a(localRegion, "sqs", "sqs.ap-southeast-2.amazonaws.com");
    a(localRegion, "iot", "iot.ap-southeast-2.amazonaws.com");
    a(localRegion, "sdb", "sdb.ap-southeast-2.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-2.amazonaws.com");
    a(localRegion, "sns", "sns.ap-southeast-2.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.ap-southeast-2.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.ap-southeast-2.amazonaws.com");
    a(localRegion, "lambda", "lambda.ap-southeast-2.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.ap-southeast-2.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.ap-southeast-2.amazonaws.com");
    a(localRegion, "ec2", "ec2.ap-southeast-2.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "kms", "kms.ap-southeast-2.amazonaws.com");
    a(localRegion, "s3", "s3-ap-southeast-2.amazonaws.com");
    localRegion = new Region("ca-central-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "autoscaling", "autoscaling.ca-central-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.ca-central-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.ca-central-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.ca-central-1.amazonaws.com");
    a(localRegion, "kms", "kms.ca-central-1.amazonaws.com");
    a(localRegion, "s3", "s3.ca-central-1.amazonaws.com");
    a(localRegion, "sns", "sns.ca-central-1.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.ca-central-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.ca-central-1.amazonaws.com");
    localRegion = new Region("eu-central-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "sqs", "sqs.eu-central-1.amazonaws.com");
    a(localRegion, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.eu-central-1.amazonaws.com");
    a(localRegion, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com");
    a(localRegion, "kms", "kms.eu-central-1.amazonaws.com");
    a(localRegion, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.eu-central-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.eu-central-1.amazonaws.com");
    a(localRegion, "iot", "iot.eu-central-1.amazonaws.com");
    a(localRegion, "lambda", "lambda.eu-central-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "sns", "sns.eu-central-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.eu-central-1.amazonaws.com");
    a(localRegion, "s3", "s3.eu-central-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.eu-central-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.eu-central-1.amazonaws.com");
    localRegion = new Region("eu-west-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "sdb", "sdb.eu-west-1.amazonaws.com");
    a(localRegion, "firehose", "firehose.eu-west-1.amazonaws.com");
    a(localRegion, "kms", "kms.eu-west-1.amazonaws.com");
    a(localRegion, "polly", "polly.eu-west-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.eu-west-1.amazonaws.com");
    a(localRegion, "iot", "iot.eu-west-1.amazonaws.com");
    a(localRegion, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com");
    a(localRegion, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com");
    a(localRegion, "machinelearning", "machinelearning.eu-west-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.eu-west-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.eu-west-1.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.eu-west-1.amazonaws.com");
    a(localRegion, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.eu-west-1.amazonaws.com");
    a(localRegion, "sns", "sns.eu-west-1.amazonaws.com");
    a(localRegion, "lambda", "lambda.eu-west-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.eu-west-1.amazonaws.com");
    a(localRegion, "email", "email.eu-west-1.amazonaws.com");
    a(localRegion, "s3", "s3-eu-west-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.eu-west-1.amazonaws.com");
    localRegion = new Region("eu-west-2", "");
    localArrayList.add(localRegion);
    a(localRegion, "autoscaling", "autoscaling.eu-west-2.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.eu-west-2.amazonaws.com");
    a(localRegion, "sqs", "sqs.eu-west-2.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "s3", "s3.eu-west-2.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.eu-west-2.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.eu-west-2.amazonaws.com");
    a(localRegion, "kms", "kms.eu-west-2.amazonaws.com");
    a(localRegion, "sns", "sns.eu-west-2.amazonaws.com");
    a(localRegion, "ec2", "ec2.eu-west-2.amazonaws.com");
    localRegion = new Region("sa-east-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "sdb", "sdb.sa-east-1.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.sa-east-1.amazonaws.com");
    a(localRegion, "sns", "sns.sa-east-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.sa-east-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.sa-east-1.amazonaws.com");
    a(localRegion, "ec2", "ec2.sa-east-1.amazonaws.com");
    a(localRegion, "s3", "s3-sa-east-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "sqs", "sqs.sa-east-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.sa-east-1.amazonaws.com");
    a(localRegion, "kms", "kms.sa-east-1.amazonaws.com");
    localRegion = new Region("us-east-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "dynamodb", "dynamodb.us-east-1.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.us-east-1.amazonaws.com");
    a(localRegion, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com");
    a(localRegion, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com");
    a(localRegion, "iot", "iot.us-east-1.amazonaws.com");
    a(localRegion, "kms", "kms.us-east-1.amazonaws.com");
    a(localRegion, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com");
    a(localRegion, "pinpoint", "pinpoint.us-east-1.amazonaws.com");
    a(localRegion, "polly", "polly.us-east-1.amazonaws.com");
    a(localRegion, "lambda", "lambda.us-east-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.us-east-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "ec2", "ec2.us-east-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.us-east-1.amazonaws.com");
    a(localRegion, "email", "email.us-east-1.amazonaws.com");
    a(localRegion, "firehose", "firehose.us-east-1.amazonaws.com");
    a(localRegion, "machinelearning", "machinelearning.us-east-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.us-east-1.amazonaws.com");
    a(localRegion, "s3", "s3.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.us-east-1.amazonaws.com");
    a(localRegion, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com");
    a(localRegion, "sdb", "sdb.amazonaws.com");
    a(localRegion, "sns", "sns.us-east-1.amazonaws.com");
    localRegion = new Region("us-east-2", "");
    localArrayList.add(localRegion);
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.us-east-2.amazonaws.com");
    a(localRegion, "ec2", "ec2.us-east-2.amazonaws.com");
    a(localRegion, "sns", "sns.us-east-2.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.us-east-2.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.us-east-2.amazonaws.com");
    a(localRegion, "polly", "polly.us-east-2.amazonaws.com");
    a(localRegion, "s3", "s3.us-east-2.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.us-east-2.amazonaws.com");
    a(localRegion, "kms", "kms.us-east-2.amazonaws.com");
    a(localRegion, "lambda", "lambda.us-east-2.amazonaws.com");
    a(localRegion, "sqs", "sqs.us-east-2.amazonaws.com");
    localRegion = new Region("us-west-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "kinesis", "kinesis.us-west-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.us-west-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "ec2", "ec2.us-west-1.amazonaws.com");
    a(localRegion, "lambda", "lambda.us-west-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.us-west-1.amazonaws.com");
    a(localRegion, "s3", "s3-us-west-1.amazonaws.com");
    a(localRegion, "sdb", "sdb.us-west-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.us-west-1.amazonaws.com");
    a(localRegion, "sns", "sns.us-west-1.amazonaws.com");
    a(localRegion, "kms", "kms.us-west-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.us-west-1.amazonaws.com");
    localRegion = new Region("us-west-2", "");
    localArrayList.add(localRegion);
    a(localRegion, "sdb", "sdb.us-west-2.amazonaws.com");
    a(localRegion, "kinesis", "kinesis.us-west-2.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "ec2", "ec2.us-west-2.amazonaws.com");
    a(localRegion, "iot", "iot.us-west-2.amazonaws.com");
    a(localRegion, "s3", "s3-us-west-2.amazonaws.com");
    a(localRegion, "firehose", "firehose.us-west-2.amazonaws.com");
    a(localRegion, "kms", "kms.us-west-2.amazonaws.com");
    a(localRegion, "sns", "sns.us-west-2.amazonaws.com");
    a(localRegion, "polly", "polly.us-west-2.amazonaws.com");
    a(localRegion, "sqs", "sqs.us-west-2.amazonaws.com");
    a(localRegion, "data.iot", "data.iot.us-west-2.amazonaws.com");
    a(localRegion, "email", "email.us-west-2.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.us-west-2.amazonaws.com");
    a(localRegion, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com");
    a(localRegion, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.us-west-2.amazonaws.com");
    a(localRegion, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com");
    a(localRegion, "lambda", "lambda.us-west-2.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.us-west-2.amazonaws.com");
    localRegion = new Region("cn-north-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "sts", "sts.cn-north-1.amazonaws.com.cn");
    a(localRegion, "s3", "s3.cn-north-1.amazonaws.com.cn");
    a(localRegion, "sqs", "sqs.cn-north-1.amazonaws.com.cn");
    a(localRegion, "dynamodb", "dynamodb.cn-north-1.amazonaws.com.cn");
    a(localRegion, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn");
    a(localRegion, "sns", "sns.cn-north-1.amazonaws.com.cn");
    a(localRegion, "autoscaling", "autoscaling.cn-north-1.amazonaws.com.cn");
    a(localRegion, "ec2", "ec2.cn-north-1.amazonaws.com.cn");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.cn-north-1.amazonaws.com.cn");
    localRegion = new Region("us-gov-west-1", "");
    localArrayList.add(localRegion);
    a(localRegion, "ec2", "ec2.us-gov-west-1.amazonaws.com");
    a(localRegion, "s3", "s3-us-gov-west-1.amazonaws.com");
    a(localRegion, "kms", "kms.us-gov-west-1.amazonaws.com");
    a(localRegion, "sqs", "sqs.us-gov-west-1.amazonaws.com");
    a(localRegion, "elasticloadbalancing", "elasticloadbalancing.us-gov-west-1.amazonaws.com");
    a(localRegion, "sts", "sts.amazonaws.com");
    a(localRegion, "sns", "sns.us-gov-west-1.amazonaws.com");
    a(localRegion, "autoscaling", "autoscaling.us-gov-west-1.amazonaws.com");
    a(localRegion, "dynamodb", "dynamodb.us-gov-west-1.amazonaws.com");
    return localArrayList;
  }
}


/* Location:              /home/qerwtr546/Documents/Vent Source/dex2jar-2.0/classes-dex2jar.jar!/com/amazonaws/regions/RegionDefaults.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */